modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="multitools"
version="1.0.0"
displayName="MultiTools"
description='''
Universal tools (Paxels) for Minecraft
'''

[[dependencies.multitools]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.multitools]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
